export enum TipoAcoes {
    LISTAR_PROJETOS = 'LISTAR_PROJETOS',
    ADICIONA_PROJETO = 'ADICIONA_PROJETO',
    ATUALIZA_PROJETO = 'ATUALIZA_PROJETO',
    REMOVE_PROJETO = 'REMOVE_PROJETO',

    LISTAR_TAREFAS = 'LISTAR_TAREFAS',
    ADICIONA_TAREFA = 'ADICIONA_TAREFA',
    ATUALIZA_TAREFA = 'ATUALIZA_TAREFA',
}
