export enum TipoMutacoes {
    DEFINIR_PROJETOS = 'DEFINIR_PROJETOS',
    DEFINIR_TAREFAS = 'DEFINIR_TAREFAS',
    NOTIFICAR = 'NOTIFICAR',
    HTTP_START = 'HTTP_START',
    HTTP_FINISH = 'HTTP_FINISH',
}
